### ISSUE TITLE
Sioyek is not responding

### ISSUE THREAD

**Issue by DOFfactory** [ahrm/sioyek#113]
Sometimes when I load a larger PDF I get this error:

![image](https://user-images.githubusercontent.com/10846169/144844519-d0a829e6-b9fd-48c4-af4b-a12fa5fb985a.png)

I do not know what is causing the issue, but if you want to troubleshoot/debug, in this case it was this document: https://op.europa.eu/en/publication-detail/-/publication/7769a148-f1f6-11e8-9982-01aa75ed71a1

I noticed that if one scrolls too quickly, it hogs the system, sometimes sioyek is able to recover from it, sometimes not. My system is updated Windows 10.

**Comment by ahrm** [comment]
I was not able to reproduce the issue. Are you using the latest commit?

**Comment by DOFfactory** [comment]
Yup, using version 1.0.0 release

**Comment by ahrm** [comment]
Can you test it on [this](https://github.com/hexomancer/sioyek/releases/download/v0.31.121/sioyek-release-windows-portable.zip) portable version and see if the issue persists?

**Comment by DOFfactory** [comment]
I think it needs further testing, but the issue does not appeared yet with this portable version. Is there any change implemented?

**Comment by ahrm** [comment]
No it's just a build of the latest version. Here is a non-portable version of the latest commit:
https://github.com/hexomancer/sioyek/releases/download/v0.31.122/sioyek-release-windows.zip

**Comment by DOFfactory** [comment]
> No it's just a build of the latest version. Here is a non-portable version of the latest commit: https://github.com/hexomancer/sioyek/releases/download/v0.31.122/sioyek-release-windows.zip

Thanks, will test this and let you know! 👍

**Comment by ahrm** [comment]
> > No it's just a build of the latest version. Here is a non-portable version of the latest commit: https://github.com/hexomancer/sioyek/releases/download/v0.31.122/sioyek-release-windows.zip
> 
> Thanks, will test this and let you know! 👍
> 
> EDIT: How is this v0.31.122 different from v1.0? Am I downgrading with this install?

This is an experimental build of the latest commit. Version 1.0.0 in release page is approximately a month old. This is not a downgrade, I just use different version numbers for experimental builds.

**Comment by ahrm** [comment]
Is the issue fixed in the new version?

**Comment by DOFfactory** [comment]
So far OK, I am closing now, if the issue reappears, I will reopen this ticket. Thanks!

**Comment by DOFfactory** [comment]
Hm, unfortunately (at least at my end) this issue still persists. I am scrolling through the PDF, highlighting, and at some random point while scrolling the whole app becomes unresponsive 😟 no idea what might be the culprit

**Comment by ahrm** [comment]
Does it happen on the same PDF file you posted?

**Comment by DOFfactory** [comment]
No, it happens on almost all PDFs. After some scrolling it freezes, have to force kill the app. I tried to identify some pattern, but there is none. Once it freezes on p. 3, the other time it is p. 12. It is all related to scrolling/page down. I usually open a PDF, I hit the `-` button couple of times to adjust the width of the text, and then I start reading, highlighting necessary parts with mouse. Then I scroll. And at some point it freezes.

**Comment by ahrm** [comment]
I couldn't be sure on what the issue is. I made some guesses and made some changes. Here is an experimental version with the new changes:

https://github.com/hexomancer/sioyek/releases/tag/v0.31.123

Please tell me if the issue still persists.

**Comment by DOFfactory** [comment]
Thanks, I tried this release (portable), the issue remains. What I did, I opened a random PDF and I scrolled up and down from the beginning of the document to the end and back. At some point if froze again (not responding in the title bar).

**Comment by ahrm** [comment]
I made another build which logs some debug information into a file named `sioyek_log.txt`. Could you run this build and send me this file after a crash (or the final parts of the file if it is too big)?

Note that this version creates pretty big log files so I don't recommend using this version for actual PDF-reading, this is only for debugging.

https://github.com/hexomancer/sioyek/releases/tag/v0.31.126

**Comment by DOFfactory** [comment]
I am closing this issue as I changed computers (with a much more powerful CPU) and I cannot reproduce the problem anymore. Thanks for the help and support, if I notice anything odd, I will reopen this case.
