### ISSUE TITLE
building from AUR: ‘class QString’ has no member named ‘back’

### ISSUE THREAD

**Issue by tgy** [ahrm/sioyek#132]
freshly tried to install from AUR and got this build error
```
pdf_viewer/ui.h: In member function ‘virtual bool FileSelector::on_text_change(const QString&)’:
pdf_viewer/ui.h:469:39: error: ‘class QString’ has no member named ‘back’
  469 |                         if (last_root.back() == QDir::separator()) {
```
on `5.16.10-arch1-1` with 
```
local/qt5-base 5.15.2+kde+r301-1 (qt qt5)
    A cross-platform application and UI framework
```

**Comment by ahrm** [comment]
Should be fixed in ec91000cd2206cb898916817235255bbf59043cd .

**Comment by tgy** [comment]
thanks. this is not fixed though, because there are other instances where this `back()` method is used but cannot be found.

see for example here:
```
➜ ag --cpp '\.back\(\)'
pdf_viewer/config.cpp
252:	user_config_paths.back().file_parent().create_directories();
253:	create_file_if_not_exists(user_config_paths.back().get_path());
254:	return user_config_paths.back();

pdf_viewer/database.cpp
646://			out_result.push_back(std::make_pair(hash, paths.back()));

pdf_viewer/input.cpp
453:	user_key_paths.back().file_parent().create_directories();
454:	create_file_if_not_exists(user_key_paths.back().get_path());
455:	return user_key_paths.back();

pdf_viewer/main_widget.cpp
1362:	//	DocumentViewState last_history = history.back();
2655:	std::wstring file_name = path_parts.back();

pdf_viewer/utils.cpp
1365:			std::string version_string = utf8_encode(parts.back().substr(1, parts.back().size() - 1));
1400:		if (path.back() == sep) {
1409:				out_partial = parts.back();
```

line 1400 is currently failing to compile when building after your fix

**Comment by ahrm** [comment]
Should be fixed in 72d2864651182140cf5682a0cdb37730cc408c46.

**Comment by tgy** [comment]
working now! thx :)
