### ISSUE TITLE
*_user.config not being read

### ISSUE THREAD

**Issue by faurehu** [ahrm/sioyek#236]
None of the files (pref_user.config and keys_user.config) have any effect on sioyek. I copy the config from the *.config file, paste, make changes in the *_user.config file and then save it. When I restart sioyek, none of the expected changes come into effect.

I'm using MacOS 12.3.1 on a M1 Max and using sioyek v1.3.330

**Comment by ahrm** [comment]
What if you put your configs in `~/.config/sioyek/*_user.config`?

**Comment by amzon-ex** [comment]
I have a *related* problem on Windows 11. In my case, I was defining the `custom_background_color` and `custom_text_color` in the `prefs_user.config` file located at `C:\ProgramData\sioyek`. However, only `custom_text_color` is being applied, leaving the background white. Only when I comment out these changes in the user config and do them directly in the `prefs.config` file, they're correctly applied.

**Comment by ahrm** [comment]
Could you share the problematic `prefs_user.config` file so I can test it?

**Comment by amzon-ex** [comment]
Sorry for being late. Here it is.
The color lines are commented out, there are two pairs and they correspond to different color schemes. I only turn on one at a time. Uploaded as txt file because .config files are not supported here:
[prefs_user.txt](https://github.com/ahrm/sioyek/files/8790621/prefs_user.txt)

**Comment by ahrm** [comment]
Should be fixed in 8c6385dd6950eaa7ced650d9e5a048e7db25a8e5.

**Comment by faurehu** [comment]
Unfortunately, the new version does not seem to fix the issue for me.

**Comment by faurehu** [comment]
Should we reopen this? Or do I create a new issue?

**Comment by ahrm** [comment]
We can reopen this issue. Unfortunately, it is difficult for me to debug mac-related issues because I don't have a mac computer. Here are a few checks:

* Which version of sioyek are you using? Are you using a pre-built binary or compiling it yourself?
* When you run sioyek from command line it should print a list of config file location that it checks.
* Note that the name of preference file is `prefs_user.config` not `pref_user.config`
* Test with a simple config file to make sure the issue is not a syntax error in config files. For example you can use this as your `prefs_user.config` file:
```
startup_commands toggle_dark_mode
```

**Comment by faurehu** [comment]
I found the issue, I had a typo in my keys file: `next_state <S-<backspace>> | <C-]>`. How embarrassing haha

**Comment by x61** [comment]
I am having this very issue where the configs are not loading up. I even reinstalled multiple times without any success. I am using the latest version 2.0.0 on mac. Here is the message I get when executed from the command line.

```default_config_path: /Applications/sioyek.app/Contents/MacOS/prefs.config
default_keys_path: /Applications/sioyek.app/Contents/MacOS/keys.config
user_config_path: [ 0 ] /Users/home/.config/sioyek/prefs_user.config
user_config_path: [ 1 ] /Users/home/Library/Application Support/sioyek/prefs_user.config
user_keys_path: [ 0 ] /Users/home/.config/sioyek/keys_user.config
user_keys_path: [ 1 ] /Users/home/Library/Application Support/sioyek/keys_user.config
database_file_path: /Users/home/Library/Application Support/sioyek/test.db
local_database_file_path: /Users/home/Library/Application Support/sioyek/local.db
global_database_file_path: /Users/home/Library/Application Support/sioyek/shared.db
tutorial_path: /Applications/sioyek.app/Contents/MacOS/tutorial.pdf
last_opened_file_address_path: /Users/home/Library/Application Support/sioyek/last_document_path.txt
shader_path: /Applications/sioyek.app/Contents/MacOS/shaders
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader```

**Comment by ahrm** [comment]
Is it possible that there is a syntax error in your config files?

**Comment by x61** [comment]
I copied the configs in keys.config and prefs.config into ~/.configs/sioyek/** as keys_user.config and prefs_user.config and tried changing the background_color in pref_user.config but there is no effect. Just tested other options and I see that changing the color of text_highlight_color works. Is background_color the correct parameter option for changing the background color?

**Comment by x61** [comment]
@ahrm, also on a separate topic, I see that `visual_mark_color` has 4 values in the prefs.config and I tried to change it  in my prefs_user.config to have 3 values but it is throwing an error saying it "requires 3 values for color but got 3". Please see the attached screenshot. I am using MacOS Monterey. 

<img width="1017" alt="Screen Shot 2023-01-21 at 18 34 27" src="https://user-images.githubusercontent.com/6430853/213894981-f8c09ca5-b412-4fc9-8784-3ccac7b021e9.png">

**Comment by ahrm** [comment]
Yeah the error message is wrong but we do need 4 colors (the last one is transparency).  

> I copied the configs in keys.config and prefs.config into ~/.configs/sioyek/** as keys_user.config and prefs_user.config

I suggest only copying the settings you want to change instead of all of them. `background_color` changes the background color of the application, if you want to change the background color of the PDF, see custom color mode in the documentation.

**Comment by x61** [comment]
Thank you
