### ISSUE TITLE
[FR] Customization for command menu

### ISSUE THREAD

**Issue by raffaem** [ahrm/sioyek#452]
The background color for the command menu, as well as the font family, font size and font color, should be customizable in config file:

![image](https://user-images.githubusercontent.com/54762742/194718176-eb7f5138-1288-4f22-af19-e1a3709cceac.png)

**Comment by ahrm** [comment]
Renamed `status_bar_color` and `status_bar_text_color` to `ui_background_color` and `ui_text_color` in b2e78e4e76b4e7810a7791e49bda4f65753c851b and now they are applied to other menus as well. Also added some other options to change the color of selected items:
```
ui_text_color 1 1 0
ui_background_color 0 0 0
ui_selected_text_color 1 0 0
ui_selected_background_color 0 1 1
```

**Comment by raffaem** [comment]
1. I don't understand. The "command menu" (if this is how it is called) seems to ignore `ui_text_color` and `ui_background_color`, while it is effectively using the `select_` version when the item is selected
2. What about `status_bar_font_size`?

**Comment by ahrm** [comment]
> I don't understand. The "command menu" (if this is how it is called) seems to ignore ui_text_color and ui_background_color, while it is effectively using the select_ version when the item is selected

Are you sure you are not overriding it with `status_bar_color`?

> What about status_bar_font_size?

We already have a `ui_font_size` option.

**Comment by raffaem** [comment]
Isn't `status_bar_color` dead? I removed it.

This is my prefs file.

If you change `ui_background_color`, the background color of the "command menu" doesn't change

```
# === DRACULA THEME === #
startup_commands		toggle_custom_color

background_color	   	0.15686 0.16471 0.21176
dark_mode_background_color 	0.15686 0.16471 0.21176
#dark_mode_contrast		0.8

text_highlight_color 		0.94510 0.98039 0.54902
visual_mark_color  		0.15686 0.16471 0.21176 0.8

search_highlight_color		0.94510 0.98039 0.54902
link_highlight_color 		0.38431 0.44706 0.64314
synctex_highlight_color		0.31373 0.98039 0.48235

highlight_color_a 		1.00000 0.72157 0.42353
highlight_color_b		0.31373 0.98039 0.48235
highlight_color_c		0.54510 0.91373 0.99216
highlight_color_d		1.00000 0.47451 0.77647
highlight_color_e		0.74118 0.57647 0.97647
highlight_color_f		1.00000 0.33333 0.33333
highlight_color_g		0.94510 0.98039 0.54902

#default_dark_mode		1

font_size			12
ui_font				FiraCode Mono

custom_background_color 	0.15686 0.16471 0.21176
custom_text_color		0.97255 0.97255 0.94902

ui_text_color 			0.97255 0.97255 0.94902
ui_background_color 		0.15686 0.16471 0.21176
ui_selected_text_color 		0.97255 0.97255 0.94902
ui_selected_background_color 	0.26667 0.27843 0.35294

status_bar_font_size    	16
```

**Comment by ahrm** [comment]
Should be fixed in c118e85e39232c2e264272691cbd95f6eb498256.

**Comment by raffaem** [comment]
This fixed the command menu but broke the status bar, which now is always black regardless of `ui_background_color` :p

**Comment by ahrm** [comment]
Can not reproduce the issue. Please post a minimal config file that has this issue.

**Comment by raffaem** [comment]
Uhm it only happens if you source an external file. It works if you put the option directly in `prefs_user.config`:

```
[raffaele@raffadora sioyek]$ cat prefs_user.config
startup_commands source_config(/home/raffaele/.config/sioyek/dracula.config)
[raffaele@raffadora sioyek]$ cat dracula.config
ui_background_color 	1 0 0	
```

**Comment by ahrm** [comment]
Should be fixed in a4eaecd5446f5f3461953fe838a21b50d5cbf499.

**Comment by raffaem** [comment]
I still see the "command window" red but the status bar black.
Same config as before.
Latest commit.

```
[raffaele@raffadora sioyek]$ git log -1
commit a4eaecd5446f5f3461953fe838a21b50d5cbf499 (HEAD -> main, upstream/main)
Author: ahrm <a.hr.mostafavi@gmail.com>
Date:   Sun Oct 9 21:07:09 2022 +0330

    Properly reload styles for statusbar when config file is changed
```

```
[raffaele@raffadora sioyek]$ cat prefs_user.config
startup_commands source_config(/home/raffaele/.config/sioyek/dracula.config)

[raffaele@raffadora sioyek]$ cat dracula.config
ui_background_color 	1 0 0	
```

![image](https://user-images.githubusercontent.com/54762742/194771597-5b38ec35-0e32-4975-8a9d-a3a2c6ea7594.png)

**Comment by ahrm** [comment]
Should be fixed in f98cb43499be3e8116b68636da23fc071ab16d34.

**Comment by raffaem** [comment]
It is fixed indeed :)

How can I set the font size for the "command menu"?

**Comment by ahrm** [comment]
```
font_size 20
```

**Comment by raffaem** [comment]
I'm sorry I find very confusing that:

The color of the text is set with `ui_text_color` for both status bar and command window.

The color of the background is set with `ui_background_color` for both status bar and command window.

But the font size is set with `font_size` for command window and `status_bar_font_size` for the status bar.

Is this deliberate?

**Comment by ahrm** [comment]
Yes, since status bar is always visible, some users want to use a very small font size for status bar and a larger font size for the rest of the UI.

**Comment by raffaem** [comment]
Fair enough.

But I would put different commands for colors also.
I'm a fan of fully customization :D
Thanks!
