### ISSUE TITLE
New coloring algorithm produces illegible colors in some cases

### ISSUE THREAD

**Issue by amanjitsk** [ahrm/sioyek#579]
The new coloring algorithm in [60de8c1](https://github.com/ahrm/sioyek/commit/60de8c1aca24e8b1a30986c3905c3877a52768e2) brings some changes for the worse when
using custom colors. For instance, when using the nord color scheme with settings
```
## Background color to use when executing `toggle_custom_color`
custom_background_color #2E3440
custom_color_mode_empty_background_color #2E3440
## Text color to use when executing `toggle_custom_color`
custom_text_color #D8DEE9
```

The image on the left is normal black/white colors, the middle is sioyek's coloring 
after the aforementioned commit, and the right image is zathura's equivalent.
I think sioyek did something similar to zathura before that commit.

![image](https://user-images.githubusercontent.com/12499495/210116758-a987c132-ba2d-401c-9f71-34333392ab51.png)

**Comment by mil-ad** [comment]
Zathura has the `recolor-keephue`. I think the new colouring algorithm is similar to having `set recolor-keephue true`

**Comment by xulongwu4** [comment]
I have been having the same issue using the new coloring algorithm in 60de8c1. @mil-ad, the picture posted by @amanjitsk with zathura is already with `recolor-keephue` set to true. If `recolor-keephue` is set to false, the whole document will be essentially black and white. The problem of non-visible bright-blue color in custom color mode is introduced by 60de8c1, and it is not a problem for other apps such as zathura/mupdf.

**Comment by xulongwu4** [comment]
It seems that this was also a problem for the dark mode, but it was fixed/improved by #554 for the dark mode.

**Comment by ahrm** [comment]
Added a `custom_color_contrast` option in ff414c3496136fadb90dcd0da5dacf219a2b3728. It provides a tradeoff between contrast and deviation from the original colors. It can have values between 0 and 1. Here are some samples with different values:
![contrast_1](https://user-images.githubusercontent.com/6392321/210171156-d1b5b780-1a7a-49dc-a5fc-80d292dd0a72.png)
![contrast_zero](https://user-images.githubusercontent.com/6392321/210171157-60624a2b-21d5-4155-aa20-f8c3a2c84b06.png)
![custom_color_contrast](https://user-images.githubusercontent.com/6392321/210171158-bd041847-bc08-464c-b668-2aaa6e8ecc9a.png)

**Comment by amanjitsk** [comment]
I still can't quite reproduce zathura's colors above (which I think are more "correct"), but this does make it readable! Thanks for the quick response!
