### ISSUE TITLE
Cropped and blurry pages

### ISSUE THREAD

**Issue by minhduc0711** [ahrm/sioyek#591]
Sioyek 2.0 does not display any PDF correctly: text are blurry and the bottom of each page is cropped out. This does not happen when I roll back to 1.5.0.

System info:
* Appimage version
* DE: sway/wayland
* DPI scaling: 1.0

![image](https://user-images.githubusercontent.com/34294427/211916052-ba97bfaf-b161-4f4e-9032-a13979b63c31.png)

**Comment by ahrm** [comment]
Can anyone else reproduce this issue?

**Comment by JoostScheffer** [comment]
I also have this all the text is blurry.

I noticed that when I use the preview feature the text is not blurry.
![image](https://user-images.githubusercontent.com/56606926/214599182-afbea411-fabf-44f4-a4b3-75dc43d8ee42.png)

In Okular it looks like this:
![image](https://user-images.githubusercontent.com/56606926/214599545-8df16ab2-3a52-4dcb-84d6-23e0f4c12316.png)

**Comment by ahrm** [comment]
What is your operating system/display resolution?

**Comment by JoostScheffer** [comment]
Sorry I forgot to add that.

I am running:
- Kubuntu 22.04
- (KDE) Plasma 5.25.5 on X11
- Qt Version 5.13.3
- Intel Mesa Xe Graphic (integrated graphics)
- My screen has a resolution of  2560x1600 (16:10) and I use 125% scaling (in Plasma).

I know this is not the most common combination of hardware and OS

If you want more info, tests or screenshots, feel free to ask.

**Comment by JoostScheffer** [comment]
Here you can see the text in the titlebar of Sioyek next to a piece of text in a pdf file
![image](https://user-images.githubusercontent.com/56606926/214679713-e87155e6-05a4-4c37-b7cd-e9434c3a982c.png)

**Comment by ahrm** [comment]
>  I use 125% scaling (in Plasma).

I assume this might be the culprit. Can you test it on 100% scaling?

**Comment by JoostScheffer** [comment]
This is indeed the case. Setting scaling to 100% resolves this issue.

Unfortunately I need the 125% scaling for other apps...
Do you have any idea as to which part of Sioyek might be causing this?

**Comment by JoostScheffer** [comment]
That does not seem to change anything

![image](https://user-images.githubusercontent.com/56606926/214840765-34710595-f8a4-4689-811f-9854d25c6e53.png)

Btw, I am using the flathub version of Sioyek, version 2.0.0 released on 12-12-2022
The path of the `prefs_user.config` that I changed is `/var/lib/flatpak/app/com.github.ahrm.sioyek/current/active/files/sioyek`

**Comment by ahrm** [comment]
We were using `devicePixelRatio` to get the display scaling which returns an int (so doesn't support fractional values for scaling). It should be fixed in 78b5904302c3e61a20117c94c3d2247109ac5c1b. You should delete `display_resolution_scale 1.25` from your config file.

**Comment by JoostScheffer** [comment]
cool!

**Comment by JoostScheffer** [comment]
I compiled the new version myself. My problem has been resolved. Thanks!

I don't know what problem @minhduc0711 had, but I am guessing that it was different from mine.

**Comment by minhduc0711** [comment]
My problem seems to be fixed as well, but I'm not sure if that was because of https://github.com/ahrm/sioyek/commit/78b5904302c3e61a20117c94c3d2247109ac5c1b or not. Anyway, big thanks to @ahrm :clap:

**Comment by lucasvreis** [comment]
When I use two screens with different fractional scaling factors, the issue is still present in one of the screens. There is something odd about it, because it only looks blurry when the window enters the second screen completely, as if a value suddenly updated and caused the issue. When the screen is only partially in the second screen the portion of it in the affected screen is not blurry. 

Here I try to record the issue with a Moire pattern, notice how the pattern changes when the window finishes moving across monitors (despite the video quality, I actually see the different Moire patterns): 
[output.webm](https://user-images.githubusercontent.com/4229115/235818005-203b197b-9212-4784-87e6-726ba2674347.webm)
