### ISSUE TITLE
Keeping PDF open for days results in high Memory consumption

### ISSUE THREAD

**Issue by jash-maester** [ahrm/sioyek#693]
**ISSUE:** Leaving PDF Files open on work computer for more than **24hrs** results in Sioyek consuming more than **3-4GB** of RAM, after which I have to close and re-open the same PDF file to reset the memory counter.
There could be caching of some sorts or some memory being allocated and not freed at runtime. What I can conclude is that a very small amount of memory is being allocated every few minutes or so which slowly accumulate to a bigger number.
It pushes browser or other stuff to swap memory pretty easily.

I don't know how to debug the issue, I would be rather interested in debugging the issue if anyone points me in the right direction. Also, I'm using the AppImage version, so the same issue could be replicated by anyone hopefully.

**Comment by ahrm** [comment]
Are you using the same PDF file or opening multiple PDF files?

**Comment by HakonHarnes** [comment]
You can debug this using tools such as Valgrind or cppcheck. Valgrind is dynamic and will check for leaks at runtime, while cppcheck will just statically analyzes the code. 

## Valgrind 

```
valgrind --leak-check=full \
      --show-leak-kinds=all \
      --track-origins=yes \
      --verbose \
      --log-file=valgrind.log \
      <path-to-sioyek-executable> <file.pdf>
```

You have to build Sioyek using the `-g` flag to obtain useful debug information (I modified the `build_linux.sh` script). Here is the leak summary for Sioyek: 

```
==316370== LEAK SUMMARY:
==316370==    definitely lost: 410,192 bytes in 25 blocks
==316370==    indirectly lost: 1,368,575 bytes in 2,738 blocks
==316370==      possibly lost: 1,350,764 bytes in 366 blocks
==316370==    still reachable: 6,015,161 bytes in 3,142 blocks
==316370==                       of which reachable via heuristic:
==316370==                         length64           : 272 bytes in 4 blocks
==316370==         suppressed: 0 bytes in 0 blocks
```

See output here: https://drive.google.com/file/d/10eX5olI5-VUjJAWd4fGZp_uUucCq-pBj/view?usp=sharing

## Cppcheck

```
cppcheck sioyek/pdf_viewer
```

See output here: https://drive.google.com/file/d/10ru1MeyEjK3yGqAgzozM1tXIaG9pDWg8/view?usp=sharing

**Comment by HakonHarnes** [comment]
The biggest offenders seem to be in the `pdf_process_Do` in `pdf_interpret.c`: 

```
==360950== 4,152,640 bytes in 3 blocks are still reachable in loss record 1,387 of 1,387
==360950==    at 0x4841888: malloc (vg_replace_malloc.c:393)
==360950==    by 0x37725B: do_scavenging_malloc (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x377385: fz_malloc (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x37DE10: fz_new_pixmap_with_data (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x37DF4A: fz_new_pixmap (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x361432: fz_decomp_image_from_stream (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x361EF0: compressed_image_get_pixmap (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x360DF4: fz_get_pixmap_from_image (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x342F01: fz_draw_fill_image (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x413774: fz_fill_image (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x47394A: pdf_show_image (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x4627EA: pdf_process_Do (in /home/hakon/sioyek-fork/build/sioyek)
```

```
==360950== 2,112,984 bytes in 2 blocks are still reachable in loss record 1,386 of 1,387
==360950==    at 0x4841888: malloc (vg_replace_malloc.c:393)
==360950==    by 0x37725B: do_scavenging_malloc (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x377385: fz_malloc (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x37DE10: fz_new_pixmap_with_data (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x37DF4A: fz_new_pixmap (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x361432: fz_decomp_image_from_stream (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x361EF0: compressed_image_get_pixmap (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x360DF4: fz_get_pixmap_from_image (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x342F01: fz_draw_fill_image (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x413774: fz_fill_image (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x473795: pdf_show_image (in /home/hakon/sioyek-fork/build/sioyek)
==360950==    by 0x4627EA: pdf_process_Do (in /home/hakon/sioyek-fork/build/sioyek)
```

**Comment by jash-maester** [comment]
@ahrm Opening single PDF file or opening multiple PDF files have the same effect i.e. RAM consumption increasing.

**Comment by jash-maester** [comment]
@HakonHarnes  Let me confirm you back tomorrow or like after few hours I will open a pdf with only text and will confirm whether this behaviour happens or not.

**Comment by ahrm** [comment]
* Do you actively use sioyek or sioyek is just opened in the background?
* Is it okay if sioyek is minimized?
* Can you share your `prefs_user.config`? Maybe there is a setting which is causing the bug?

**Comment by jash-maester** [comment]
@ahrm yes, I actively use sioyek most of the time, when I left it overnight, it was also running in the foreground. Although I use DWM with slock lockscreen and my screen was locked.
I usually have a browser and sioyek open. Usually I never open stuff and go, but accidentally discovered this issue.

**Comment by ahrm** [comment]
> @HakonHarnes Let me confirm you back tomorrow or like after few hours I will open a pdf with only text and will confirm whether this behaviour happens or not.

Any updates on this?

**Comment by jash-maester** [comment]
@ahrm @HakonHarnes  Sorry for the late reply, I was ill for the last few days.
I can confirm opening up a pdf with only text document does not cause memory leaks or RAM usage blowing up.
To test it, I created a pdf file with only text and opened it with Sioyek. Left it open for 2 days not a single MB of RAM was consumed more.

**Comment by HakonHarnes** [comment]
> I can confirm opening up a pdf with only text document does not cause memory leaks or RAM usage blowing up.

That confirms my suspicion that the memory leak is related to how images are handled. It also agrees with Valgrind which reports the biggest offenders are in the `pdf_process_Do` function (`pdf_show_image`) in `pdf_interpret.c`. 

@ahrm Are images loaded and freed on demand? That is, the image is lazily loaded when viewing the page for the first time and freed later when viewing a different page. Could it be that the mechanism of freeing images is somehow not working as intended?

**Comment by ahrm** [comment]
> @ahrm Are images loaded and freed on demand? That is, the image is lazily loaded when viewing the page for the first time and freed later when viewing a different page. Could it be that the mechanism of freeing images is somehow not working as intended?

No, we don't do anything special about images. We just use the MuPDF's pdf rendering function. I have not been able to reproduce this issue even on PDFs with images. So I assume either it was some other bug in sioyek which caused the leak or maybe there was no leak at all? Note that when using sioyek to open many documents, we don't release the previous documents (this is by design so for example going back to the previous document is fast and simple) maybe the original memory usage was caused because sioyek was used to open other documents before the last one?

@jash-maester can you still reproduce the bug on the original PDF which caused the issue?

**Comment by HakonHarnes** [comment]
> I have not been able to reproduce this issue even on PDFs with images.

@ahrm This is on Windows, right? I can try to see if I replicate the issue on Arch Linux. Maybe it's Linux-specific, or specific to the AppImage build for Linux.

**Comment by ahrm** [comment]
> @ahrm This is on Windows, right?

Yes.

**Comment by HakonHarnes** [comment]
> The biggest offenders seem to be in the `pdf_process_Do` function in `pdf_interpret.c`:

This file is in MuPDF, so I wonder if the memory leak is due to a bug in MuPDF. I wonder if updating to the latest version of MuPDF will resolve the issue.

@ahrm Perhaps this is related: https://bugs.ghostscript.com/show_bug.cgi?id=705621.

**Comment by ahrm** [comment]
> > The biggest offenders seem to be in the `pdf_process_Do` function in `pdf_interpret.c`:
> 
> This file is in MuPDF, so I wonder if the memory leak is due to a bug in MuPDF. I wonder if updating to the latest version of MuPDF will resolve the issue.
> 
> @ahrm Perhaps this is related: https://bugs.ghostscript.com/show_bug.cgi?id=705621.

Wow, I opened that issue myself but completely have forgotten about it! Anyway, which version of sioyek are you using (main branch or development branch?). We don't use `FZ_STEXT_PRESEVE_IMAGES` in the main branch anymore, but we do use it again in the development branch, I also have upgraded mupdf in the development branch (not to the newest version but a newer version).

**Comment by machitgarha** [comment]
I also encounter the same issue. When I open multiple PDFs and switch between them and never close any of them, the memory consumption starts to rise. Two times even my Linux machine froze and systemd-oomd killed Sioyek because of high memory usage.

Are you welcomed to a PR if I start to work on it, @ahrm? I'm not sure if I can fix, but I would try my best based on the time I have.

**Comment by ahrm** [comment]
Depends on the size of the change, if it is just a few lines of code or an obviour bug then yes, but if it is very large then no.

**Comment by machitgarha** [comment]
Can you clarify on what do you mean by large? Is it okay to do a large PR step-by-step, and keep each commit small, so the review process would be easy?

Also, as I'm not currently familiar with the code, I don't know how many lines I should change to fix possible memory leaks. Yesterday I read the documentation of Valgrind, and it noted that one should fix the reported problems in order, because they might depend on each other, or otherwise debugging would become troublesome.

**Comment by ahrm** [comment]
I expect if there is a memory leak fixing it should probably take less than 10 lines of code. If it is more than that, I would prefer you just tell me what the bug is and I will fix it myself.

**Comment by machitgarha** [comment]
So like if there are ten memory leaks, it should be less than 100 lines? And may I ask you why are you not willing to accept larger changes?

**Comment by ahrm** [comment]
I doubt that there are many memory leaks (that matter). I don't want to accept larger changes because it is hard for me to verify them, is it actually faster for me to implement the fixes myself if I know what the bug is.

**Comment by machitgarha** [comment]
After some trial and error, I found how to reproduce the problem.

1. Open a PDF in Sioyek.
2. Enter `:new_window` command, multiple times.
3. Close the newly opened windows (keeping at least one open).
4. Repeat steps 2 and 3, and measure memory usage.

With every opening and closing, the memory usage should increase. The expected result is that, when a new window is closed, all memory associated with it gets reclaimed.

**Comment by machitgarha** [comment]
I just skimmed some parts of the code. Isn't the problem related to the use of manual memory management? Using smart pointers would be better, wouldn't they?

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/5a2620277de4d2c77ee523e59f120a364bcd3202. The memory leak was due to an idiotic decision (by me) to have a `PdfRenderer` for each widget (which were then not freed when the widget was closed). The correct approach was to have a single `PdfRenderer` for the whole application (which is what I assumed was the case, I guess when implementing multiple windows, I intended to do this after getting the windows working but I forgot to actually do it).

By the way this serves as a perfect example of why using a smart pointer is not always a good idea. If I had used `unique_ptr` for example, sure enough, there would be no memory leak, but then we would never be notified of this issue (where there is a `PdfRenderer` per window) which is a serious efficiency problem.

**Comment by machitgarha** [comment]
@ahrm, thanks for the quick fix, however, as I tested, it doesn't seem to fix the problem entirely. It did decrease the growth rate of memory usage over time, but still memory is leaked.

Looking at the change you just did, I disagree with your point about smart pointers. Before the change, if they were used, at the very least the `PdfRenderer` for a closed window would be deleted, so there would be no memory leak at least. It has nothing to do with the shared use of `PdfRenderer`: The change can be noticed and done either way, whether the memory is managed manually or using smart pointers.

The main purpose of smart pointers is to ensure every dynamically allocated memory is freed eventually time (there is also `ptr.reset()` for sooner deallocation). It doesn't automatically solve all high memory usage problems.

**Comment by ahrm** [comment]
> Before the change, if they were used, at the very least the PdfRenderer for a closed window would be deleted, so there would be no memory leak at least

You merely repeated what I said. If that was the case, the problem would be much less noticeable. I prefer problems in my program to be **more** noticeable not less noticeable.

Anyway, I am not going to discuss this further with you, let's agree to disagree.
