### ISSUE TITLE
Switching pages/slides very fast causes the screen to become momentarily blank

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#923]
Switching pages/slides very fast causes the screen to become momentarily blank. E.g., turn on presentation mode, keep pressing down an arrow key, you'll see a blank screen every so often. The reason I noticed this is that I like to keep pressing down the arrow keys to quickly move between slides, but I can't reliably see the slides to know when I should release the key.

**Comment by NightMachinery** [comment]
This also happens even with a single key press, if I do not use the arrow keys. E.g., if I use `move_down` etc., I often see a blank screen before the new page is shown.

**Comment by ahrm** [comment]
Well it does take time to render pages. We do try to prerender the next page in presentation mode but it is possible to see a blank page if a page takes too long to render. Added some config options to configure the number of pre-rendered pages in https://github.com/ahrm/sioyek/commit/287d8bf8def8d5f8148bf0fa9bcdf8125a0c184b . Setting the `num_prerendered_next_slides` to a high value should reduce the flickering (at the cost of memory consumption) but it is impossible to completely remove flickering in all cases.

**Comment by NightMachinery** [comment]
@ahrm Can we also prerender previous pages with a similar setting?
Also, it seems commands such as `move_down` are not using the prerendered pages.

**Comment by ahrm** [comment]
Yes, we also have a `num_prerendered_prev_slides` config option.

**Comment by NightMachinery** [comment]
@ahrm Another thing I noticed; turning the presentation mode on significantly worsens this problem (when using `move_down` instead of `move_right`). It's much better in the normal mode.

**Comment by ahrm** [comment]
Closing as this is impossible to fix in general. You can reduce the effect by setting prerendered slides to a high value (at the cost of memory consumption).

**Comment by NightMachinery** [comment]
@ahrm I have added:
```
num_prerendered_prev_slides 100
num_prerendered_next_slides 100
```
to my config, and it works if I use `move_left` while in presentation mode. But if I use `move_down`, it will always flicker. In particular, I use these shortcuts to move between slides:
```
next_page;fit_to_page_height;goto_top_of_page .
previous_page;fit_to_page_height;goto_top_of_page ,
```
And these two also cause a flicker WHEN the presentation mode is turned on.

**Comment by ahrm** [comment]
You were right, there was a bug which prevented utilization of prerendered pages. It should be fixed in https://github.com/ahrm/sioyek/commit/7db494950f314e3c178ebf373c270ddfeb04c944. Note that the prerendered pages config while we are not in presentation mode is different and is called `prerendered_page_count`. So you need to add something like this to `prefs_user.config`:
```
prerendered_page_count 5
```

Also I recommend setting `num_prerendered_prev_slides` to a much lower value now, lest sioyek might explode.

**Comment by NightMachinery** [comment]
Thanks. 

The commit didn't seem to change anything for me though 😅 . I am using:
```
num_prerendered_prev_slides 20
num_prerendered_next_slides 20
prerendered_page_count 20
```
I don't see any flicker if I don't have presentation mode turned ON, but if I do, using the commands `move_left` etc. (that I listed in my previous comment) causes a flicker.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/aee802d479256dc4dff2f7fa419aba1e5d9858eb.

**Comment by NightMachinery** [comment]
> Should be fixed in [aee802d](https://github.com/ahrm/sioyek/commit/aee802d479256dc4dff2f7fa419aba1e5d9858eb).

Thanks, it is indeed solved for the commands I mentioned. But the issue remains for other commands such as `screen_down`.

**Comment by ahrm** [comment]
Should be fixed in all commands in https://github.com/ahrm/sioyek/commit/534d2195484c91b38caab54cb4fcea3a904c4fe8.

**Comment by NightMachinery** [comment]
Thanks, it all seems good.
