### ISSUE TITLE
[Bug] `should_warn_about_user_key_override` is not respected

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#948]
Setting the following in `prefs_user.config`: 

```
should_warn_about_user_key_override 0
```

Does not suppress the warnings, e.g.: 

```
Warning: unmapping goto_toc because of toggle_highlight which uses th
```

**Solution**

Check if `should_warn_about_user_key_override` is set in the if statement: 

https://github.com/ahrm/sioyek/blob/f83606cdc414ef9c7575752ccfffdd5b60646eca/pdf_viewer/input.cpp#L2592-L2594

**Comment by ahrm** [comment]
Should be fixed in this commit in development branch: https://github.com/ahrm/sioyek/commit/30ac9b4e2c0f2d82268bc249bf83dd125f56d721.

**Comment by HakonHarnes** [comment]
@ahrm I still get the warning message. Commit https://github.com/ahrm/sioyek/commit/30ac9b4e2c0f2d82268bc249bf83dd125f56d721 seems to address warnings on the format: 

```
Warning: key defined in ...
``` 

But I want to suppress warnings in the format: 

```
Warning: unmapping .... because of .... which uses ...
```

Relevant lines should be: 

https://github.com/ahrm/sioyek/blob/f83606cdc414ef9c7575752ccfffdd5b60646eca/pdf_viewer/input.cpp#L2592-L2594

**Comment by ahrm** [comment]
Oh, I misunderstood completely, I actually made it more likely to get warnings in that commit.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/0d0afdf36e0149b55ee98a08cc1ee7929cec76b4.
